### ISSUE TITLE
Contracts deployed with truffle can't be verified

### ISSUE THREAD

**Issue by alcuadrado** [nomiclabs/truffle-flattener#12]
@tomasienrbc reported that if he deploys a contract with Truffle he can't verify it in etherscan with the output of truffle-flattener.

**Comment by tomasienrbc** [comment]
Absolutely! Actually, any example will work. The output of the truffle-flattener command is never the same bytecode as Truffle produces from what I can tell because there is additional "file" commands and spacing added in truffle-flattener that Truffle does not add in its compiler. The compiler should ignore spacing and comments but it doesn't.

Have you been able to to verify contracts using Truffle-Flattener? I suppose it's possible I'm doing something wrong but so far I haven't been able to make it work.

**Comment by tomasienrbc** [comment]
My solution has been to use truffle-flattener to flatten the contract and just add a new file with that Solidity code, then deploy that. That's the best I could come up with.

**Comment by alcuadrado** [comment]
I can reproduce it. I don't use `truffle migrate` normally, but I want `truffle-flattener` to work with it too. Thanks for reporting this.

**Comment by tomasienrbc** [comment]
Ah! Makes sense.

**Comment by aleybovich** [comment]
@alcuadrado are you planning to fix this issue?

**Comment by alcuadrado** [comment]
@aleybovich I'm pretty busy right now. Hopefully I'll have enough time for this soonish. But I can help anyone that wants to tackle it.

**Comment by haggins** [comment]
I'm also in need of this feature since solidity-flattener is not working with oraclize contracts. Have you been working on this @alcuadrado ?

**Comment by alcuadrado** [comment]
@haggins this is a known limitation. I recommend flattening the contracts before deploying them. If you have already deployed them you can use [solidity-flattener](https://github.com/BlockCatIO/solidity-flattener). 

I'm closing this issue as I have no intention to fix it, as it's not possible within a reasonable time. `solidity-flattener` uses a binary `solc` installation, which has some features that aren't exposed in `solc-js`.
